### ISSUE TITLE
Assignment2

### ISSUE THREAD

**Issue by blackboxlogic** [jvstone/Cos470#2]
Regarding;
https://github.com/jvstone/Cos470/blob/c4e665877ca064d74458ce2641d0ab743f7e8939/Assignment2/DollarAddresses/DollarAddresses/DollarAddressHelper.cs#L28
Were there nulls in the dataset?

**Comment by jvstone** [comment]
There weren't, I added that while writing unit tests. I had added a test where the input was null and I wanted to make it handle it without an exception.
